services:
  postgres:
    image: postgres:15
    container_name: mlflow_postgres
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    ports:
      -"5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped